# Generated by Django 2.1.1 on 2018-11-13 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('email', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('public_name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('institution', models.CharField(max_length=100)),
            ],
        ),
    ]
